# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7322f80c617dc0a3661fb91223fc8780f426e59179229e4b86a915cce9ff4b4612a9c250f4c1eccacf3930156b782afdf18cf76462f2baa9b1a16624e3b8f7d

test:
  secret_key_base: 48006667877a4f735443e9eadd195ef509e09883d3be91cb1581691df6270076b8b21b8161277e78294c57ff6df8f30f19a5f428be9ce540173d92505e62ead9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
